# Generated by Django 4.2.4 on 2023-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paula_pinto_FINAL_app', '0002_alter_inscrito_id_persona_alter_inscrito_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='id_persona',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
