# Generated by Django 4.2.4 on 2023-12-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paula_pinto_FINAL_app', '0006_alter_inscrito_institucion_alter_institucion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paula_pinto_FINAL_app.institucion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
