# Generated by Django 4.2.4 on 2023-12-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paula_pinto_FINAL_app', '0007_alter_inscrito_institucion_alter_institucion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
